#ifndef MyAppVersion
#define MyAppVersion "1.0.0"
#endif
#ifndef DistRoot
#define DistRoot "..\dist\Payload"
#endif

#define MyAppName "AetherPC"
#define MyAppPublisher "Sebastián Leyton"
#define MyAppURL "https://github.com/sLEYTONs"
#define MyAppExeName "AetherPC.exe"

[Setup]
AppId={{8F3A2C1B-9D4E-4A71-B2C8-1E6F0A9D7B33}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppCopyright=Copyright © Sebastián Leyton
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
AllowNoIcons=yes
OutputDir=..\dist\Installer
OutputBaseFilename=AetherPC_Setup
SetupIconFile=..\src\AetherPC.App\Assets\Brand\AetherPC.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
VersionInfoVersion={#MyAppVersion}.0
VersionInfoCompany={#MyAppPublisher}
VersionInfoCopyright=Copyright © Sebastián Leyton
VersionInfoDescription=Asistente técnico para Windows
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
MinVersion=10.0
UsePreviousAppDir=yes
DisableWelcomePage=no
CloseApplications=force
CloseApplicationsFilter=AetherPC.exe,Uninstall AetherPC.exe
RestartApplications=no
SetupMutex=AetherPCSetup_8F3A2C1B
UninstallRestartComputer=no

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
spanish.DesktopIcon=Crear acceso directo en el escritorio
spanish.LaunchApp=Abrir AetherPC
spanish.DataCaption=Datos de AetherPC
spanish.DataPrompt=¿Qué hacer con los datos generados por AetherPC?%n(ajustes, historial y caché en %%LocalAppData%%\AetherPC)%n%nLas optimizaciones aplicadas a Windows no se revierten.
spanish.KeepData=Conservar configuración y datos
spanish.WipeData=Eliminar todos los datos de AetherPC
spanish.CloseRunning=AetherPC está en ejecución y se cerrará para continuar.
english.DesktopIcon=Create a desktop shortcut
english.LaunchApp=Launch AetherPC
english.DataCaption=AetherPC data
english.DataPrompt=What should be done with data generated by AetherPC?%n(settings, history and cache in %%LocalAppData%%\AetherPC)%n%nWindows optimizations applied by AetherPC are not reverted.
english.KeepData=Keep settings and data
english.WipeData=Delete all AetherPC data
english.CloseRunning=AetherPC is running and will be closed to continue.

[Tasks]
Name: "desktopicon"; Description: "{cm:DesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Fuente = dist\Payload (layout launcher + app\). Nunca Portable.
Source: "{#DistRoot}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "Uninstall AetherPC.cmd,Uninstall-AetherPC.ps1,*.pdb,*.sys,createdump.exe,AetherPC_Portable.exe"

[Dirs]
Name: "{app}\app"

[InstallDelete]
; Actualización: layout plano anterior (cientos de DLL en la raíz) → ahora viven en app\.
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\*.json"
Type: files; Name: "{app}\*.config"
Type: files; Name: "{app}\*.xml"
Type: files; Name: "{app}\*.pdb"
Type: files; Name: "{app}\*.sys"
Type: files; Name: "{app}\createdump.exe"
Type: files; Name: "{app}\AetherPC_Portable.exe"
Type: files; Name: "{app}\Uninstall-AetherPC.cmd"
Type: files; Name: "{app}\Uninstall-AetherPC.ps1"
Type: files; Name: "{app}\Uninstall AetherPC.cmd"
Type: files; Name: "{app}\unins000.exe"
Type: files; Name: "{app}\unins000.dat"
Type: files; Name: "{app}\unins000.msg"
Type: filesandordirs; Name: "{app}\es"
Type: filesandordirs; Name: "{app}\en"
Type: filesandordirs; Name: "{app}\uninstall"
Type: filesandordirs; Name: "{app}\languages"
Type: filesandordirs; Name: "{app}\runtimes"
Type: filesandordirs; Name: "{app}\native"
Type: filesandordirs; Name: "{app}\assets"
Type: filesandordirs; Name: "{app}\lib"
Type: filesandordirs; Name: "{app}\app\lib"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Comment: "Asistente técnico Windows"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; shellexec: ShellExecute muestra UAC (requireAdministrator). Sin esto, CreateProcess da error 740.
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchApp}"; Flags: nowait postinstall skipifsilent shellexec

[UninstallDelete]
Type: files; Name: "{app}\AetherPC.sys"
Type: files; Name: "{app}\AetherPC_Bench.tmp"
Type: files; Name: "{app}\*.sys"
Type: files; Name: "{app}\*.pdb"
Type: files; Name: "{app}\unins000.exe"
Type: files; Name: "{app}\unins000.dat"
Type: files; Name: "{app}\unins000.msg"
Type: files; Name: "{app}\Uninstall AetherPC.exe"
Type: files; Name: "{app}\Uninstall AetherPC.dat"
Type: files; Name: "{app}\Uninstall AetherPC.msg"
Type: filesandordirs; Name: "{app}\uninstall"
Type: filesandordirs; Name: "{app}\app"
Type: filesandordirs; Name: "{app}"

[Code]
var
  GDeleteUserData: Boolean;
  GAskedUserData: Boolean;

function KillAetherPC(): Boolean;
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM AetherPC.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := True;
end;

function StopAetherPCDriver(): Boolean;
var
  ResultCode: Integer;
begin
  { Solo el servicio del driver extraído por AetherPC. No tocar WinRing0 genérico. }
  Exec('sc.exe', 'stop R0AetherPC', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('sc.exe', 'delete R0AetherPC', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('sc.exe', 'stop AetherPC', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('sc.exe', 'delete AetherPC', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := True;
end;

procedure CleanupAetherPCData();
var
  LocalDir, DriversDir: String;
begin
  LocalDir := ExpandConstant('{localappdata}\AetherPC');
  DriversDir := LocalDir + '\drivers';
  if DirExists(DriversDir) then
    DelTree(DriversDir, True, True, True);
  if DirExists(LocalDir) then
    DelTree(LocalDir, True, True, True);
end;

function CmdLineParamExists(const Value: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
  begin
    if CompareText(ParamStr(I), Value) = 0 then
    begin
      Result := True;
      Exit;
    end;
  end;
end;

function AskDeleteUserData(): Boolean;
var
  Form: TSetupForm;
  Prompt: TNewStaticText;
  KeepBtn, WipeBtn: TNewRadioButton;
  OKBtn: TNewButton;
begin
  Result := True;
  Form := CreateCustomForm(ScaleX(480), ScaleY(230), False, True);
  try
    Form.Caption := CustomMessage('DataCaption');
    Form.Position := poScreenCenter;

    Prompt := TNewStaticText.Create(Form);
    Prompt.Parent := Form;
    Prompt.Caption := CustomMessage('DataPrompt');
    Prompt.Left := ScaleX(16);
    Prompt.Top := ScaleY(16);
    Prompt.Width := ScaleX(448);
    Prompt.Height := ScaleY(70);
    Prompt.AutoSize := False;
    Prompt.WordWrap := True;

    KeepBtn := TNewRadioButton.Create(Form);
    KeepBtn.Parent := Form;
    KeepBtn.Caption := CustomMessage('KeepData');
    KeepBtn.Left := ScaleX(16);
    KeepBtn.Top := ScaleY(96);
    KeepBtn.Width := ScaleX(448);
    KeepBtn.Height := ScaleY(22);

    WipeBtn := TNewRadioButton.Create(Form);
    WipeBtn.Parent := Form;
    WipeBtn.Caption := CustomMessage('WipeData');
    WipeBtn.Left := ScaleX(16);
    WipeBtn.Top := ScaleY(124);
    WipeBtn.Width := ScaleX(448);
    WipeBtn.Height := ScaleY(22);
    WipeBtn.Checked := True;

    OKBtn := TNewButton.Create(Form);
    OKBtn.Parent := Form;
    OKBtn.Caption := SetupMessage(msgButtonOK);
    OKBtn.Left := Form.ClientWidth - ScaleX(100);
    OKBtn.Top := ScaleY(180);
    OKBtn.Width := ScaleX(84);
    OKBtn.ModalResult := mrOk;
    OKBtn.Default := True;

    if Form.ShowModal = mrOk then
      Result := WipeBtn.Checked
    else
      Result := False;
  finally
    Form.Free;
  end;
end;

function UninstallerRegKey(): String;
begin
  Result := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{8F3A2C1B-9D4E-4A71-B2C8-1E6F0A9D7B33}_is1';
end;

procedure HideFile(const Path: String);
var
  ResultCode: Integer;
begin
  if FileExists(Path) then
    Exec('attrib.exe', '+H +S "' + Path + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure RenameInnoUninstaller();
var
  OldExe, OldDat, OldMsg, NewExe, NewDat, NewMsg: String;
begin
  OldExe := ExpandConstant('{uninstallexe}');
  OldDat := ChangeFileExt(OldExe, '.dat');
  OldMsg := ChangeFileExt(OldExe, '.msg');
  NewExe := ExpandConstant('{app}') + '\Uninstall AetherPC.exe';
  NewDat := ExpandConstant('{app}') + '\Uninstall AetherPC.dat';
  NewMsg := ExpandConstant('{app}') + '\Uninstall AetherPC.msg';

  if CompareText(ExtractFileName(OldExe), 'Uninstall AetherPC.exe') = 0 then
  begin
    HideFile(NewDat);
    HideFile(NewMsg);
    Exit;
  end;

  if FileExists(NewExe) then DeleteFile(NewExe);
  if FileExists(NewDat) then DeleteFile(NewDat);
  if FileExists(NewMsg) then DeleteFile(NewMsg);

  if FileExists(OldExe) then
  begin
    if not RenameFile(OldExe, NewExe) then
    begin
      CopyFile(OldExe, NewExe, False);
      DeleteFile(OldExe);
    end;
  end;
  if FileExists(OldDat) then
  begin
    if not RenameFile(OldDat, NewDat) then
    begin
      CopyFile(OldDat, NewDat, False);
      DeleteFile(OldDat);
    end;
  end;
  if FileExists(OldMsg) then
  begin
    if not RenameFile(OldMsg, NewMsg) then
    begin
      CopyFile(OldMsg, NewMsg, False);
      DeleteFile(OldMsg);
    end;
  end;

  HideFile(NewDat);
  HideFile(NewMsg);

  if FileExists(NewExe) then
  begin
    RegWriteStringValue(HKA, UninstallerRegKey(), 'UninstallString', '"' + NewExe + '"');
    RegWriteStringValue(HKA, UninstallerRegKey(), 'QuietUninstallString', '"' + NewExe + '" /SILENT');
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    RenameInnoUninstaller();
end;

function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM AetherPC.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM AetherPC_Portable.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := True;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM AetherPC.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM AetherPC_Portable.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := True;
end;

procedure EnsureUserDataChoice();
begin
  if GAskedUserData then
    Exit;
  GAskedUserData := True;
  if UninstallSilent then
    GDeleteUserData := CmdLineParamExists('/DELETEUSERDATA')
  else
    GDeleteUserData := AskDeleteUserData();
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    KillAetherPC();
    StopAetherPCDriver();
    EnsureUserDataChoice();
    if GDeleteUserData then
      CleanupAetherPCData();
  end;
  if CurUninstallStep = usPostUninstall then
  begin
    KillAetherPC();
    if GDeleteUserData then
      CleanupAetherPCData();
  end;
end;
